spring:
  application:
    name: payment-consumer

  datasource:
    name: payment-datasource
    url: jdbc:postgresql://localhost:5432/kafka_demo
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-gid
      auto-offset-reset: earliest

topic:
  payment-topic: payment_topic

server:
  port: 8080

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
    '[com.zaxxer.hikari]': OFF
    '[org.hibernate]': OFF